### ISSUE TITLE
Price indices do not have a unit

### ISSUE THREAD

**Issue by hettieboonman** [openENTRANCE/nomenclature#118]
In the file economy.yaml there are quite some variables that are (price) indices. These price indices have no unit. For example: 

Product Price Index|<Product>:
   description: Price index on <this product> level, relative to base year 2011
   note: The index equals 1 in 2011, the reference year
   unit: ''

Daniel wrote in an email (12-11-2020) the following: 

"I realized when I saw your message that we are having a problem with this kind of units data (where there is no unit) for writing to the database). For now, can you please simply add a „-„ (minus sign) when uploading test scenarios until we fix this?"

However, this minus sign does not work when we try to upload the data. Could we add a unit for all indices where a unit is missing? The name of the unit could simply be 'index'.  

Greets, Paolo and Hettie

**Comment by danielhuppmann** [comment]
Thanks @hettieboonman for (again) raising this issue - I was over-optimistic that we could fix the underlying issue in the database infrastructure earlier this year (we're still working on that as part of a larger revamping).

Either "index" or "-" would work - could you start a PR where you add it to the relevant variables?
