### ISSUE TITLE
Define structure for regions

### ISSUE THREAD

**Issue by danielhuppmann** [openENTRANCE/nomenclature#3]
This should provide instruction on how to define region names consistently, including a naming convention for overlapping regions (`EU`, `EU + UK`, `EU + UK, NO, CH`, `EU excluding MT, CY`, ...).

See the `CL_AREA` at the [SDMX global registry](https://registry.sdmx.org/items/codelist.html) for a template.

Region levels to be defined:
 - [x] aggregate regions
 - [x] list of countries
 - [x] sub-country specifications following the NUTSx classification
 - [x] other required spatial definitions (city, ...)

Required explanation:
 - [x] how to deal with directional data

**Comment by sandrinecharousset** [comment]
I copy here the discussion about sub-country levels, which can be found 
- in a [commit in my fork where I edited the readme](https://github.com/sandrinecharousset/nomenclature/commit/703e26ddaca98bffd3c9514488d3319e73e0ac63)
- in #12 (but was at the wrong place)

**Comment by danielhuppmann** [comment]
Thank you @sandrinecharousset for raising this issue. I suggest the following approach:

Add a file `subcountry-regions.yaml` following the implementation of `aggregate-regions.yaml`, where each entry has the following structure:

```
<name of region>:  # should be composed of the country name plus a meaningful identifier
   country: <parent country>  # must be a member of `countries.yaml`
   # optional attributes to be used as appropriate
   definition: <list of NUTS-x codes>  # must be a composed of members of `nuts[1/2/3].yaml`
   notes: <any relevant information, e.g., reference to another project or model documentation>
   source: <link to a document specifying this region>
```

I would not introduce any information about which subregions add up to the total country, because this could quickly become ambiguous, example based on @sandrinecharousset's comment:

 - one model uses `IT_N + IT_S`
 - another model uses `52_IT + 53_IT + IT_S`

So I would leave the responsibility of providing correct sub-country data to the modelling team.
