### ISSUE TITLE
Add variables for battery

### ISSUE THREAD

**Issue by sebastianzwickl** [openENTRANCE/nomenclature#50]
I would like to start a short discussion about variable names (to prevent confusing variable names).
We want to provide the output curves of decentralized batteries (State of Charge and Output Power of battery) to the platform. 

From my point of view, we have to add these variables. I suppose the following variable name for the **State of Charge**: `Actual Storage|Electricity|Battery` which is analogous to the already existing variable `Maximum Storage|Electricity|Hydro|Pumped Storage`. However, `State of Charge|Electricity|Battery` could be more intuitive.

Furthermore, we suppose the names `Input Power|Electricity|Battery` and 
`Output Power|Electricity|Battery` for the electricity consumed (stored) and delivered by the batteries. 

I just want to cross-check in terms of intuitive and consistent variable names.

**Comment by sebastianzwickl** [comment]
thank you @erikfilias for your answer. That would address our issue. However, I would suggest adding
 `Maximum Discharge|Electricity|Energy Storage System:`
`description: Maximum discharge when consuming energy from the energy storage system unit.`
`unit: MW`
As far as I have seen, #35 just needs to be merged - so the PR would be a nice next step.

**Comment by erikfilias** [comment]
> thank you @erikfilias for your answer. That would address our issue. However, I would suggest adding
> `Maximum Discharge|Electricity|Energy Storage System:`
> `description: Maximum discharge when consuming energy from the energy storage system unit.`
> `unit: MW`
> As far as I have seen, #35 just needs to be merged - so the PR would be a nice next step.

Totally agree. Thanks @sebastianzwickl.

**Comment by sandrinecharousset** [comment]
> From openTEPES variables, we have the following variables related to ESS (#32 ):
> 
> ```
> Maximum Energy Charge|Electricity|Energy Storage System:
>    description: This is the upper bound that energy storage system could charge energy at time "t".
>    unit: GWh
> 
> Initial Storage Level|Electricity|Energy Storage System:
>    description: Initial energy stored in the energy storage system unit at first load level. (ESS that includes hydro, battery, etc.)
>    unit: GWh
> 
> Maximum Charge|Electricity|Energy Storage System:
>    description: Maximum charge when storing energy the energy storage system unit.
>    unit: MW
> 
> Maximum Storage|Electricity|Energy Storage System:
>    description: Maximum energy that can be stored by the energy storage system unit.
>    unit: GWh
> 
> Minimum Storage|Electricity|Energy Storage System:
>    description: Minimum energy that can be stored by the energy storage system unit.
>    unit: GWh
> 
> Spillage|Electricity|Energy Storage System:
>    description: Energy spillage that could not be stored by an energy storage system (ESS). Several energy models include spillage variables related to renewable energy production; however, another way is to include a spillage variable to the ESS unit since it is the last sink of the power network.
>    unit: GWh
> 
> Stored Energy Inventory|Electricity|Energy Storage System:
>    description: State of the stored energy by ESS
>    unit:  GWh
> ```
> 
> We'll add these variables and other ones in a new PR only related to power plants after merging #35 .

@erikfilias , what is the difference between Maximum Energy Charge and Maximum Storage?
regarding Stored Energy Inventory, maybe it could be named Stored Energy (without inventory which I do not find usefull)?
What about discharge variables? eg Maximum Discharge, Minimum Discharge? 
We are also thinking of the variables we would need for plan4eu in terms of short term storage. We probably will need some additionnal variables related to charge/discharge gradients and perhaps also time frames. (work ongoing)

**Comment by sandrinecharousset** [comment]
@sebastianzwickl 
> We want to provide the output curves of decentralized batteries (State of Charge and Output Power of battery) to the platform.
> 
> From my point of view, we have to add these variables. I suppose the following variable name for the **State of Charge**: `Actual Storage|Electricity|Battery` which is analogous to the already existing variable `Maximum Storage|Electricity|Hydro|Pumped Storage`. 
However, `State of Charge|Electricity|Battery` could be more intuitive.

=> Maximum Storage|Electricity|Hydro|Pumped Storage is a constraint, it is the maximum amount of energy that could be stored in the 'pumped storage' system, then it is not 'state of charge'
> 
In general for most variables we have a varaible that is the current state, and also a maximum and minimum: eg. Active Power, Maximum Active Power, Minimum Active Power, which should exist for all systems that sends power to the grid (or virtually sends power, like eg demand-response); or Volume, Minimum Volume, Maximum Volume ; Storage, Minimum Storage, Maximum Storage

> Furthermore, we suppose the names `Input Power|Electricity|Battery` and
> `Output Power|Electricity|Battery` for the electricity consumed (stored) and delivered by the batteries.
>=> We should find a 'compromise' name that would be the same for everyone
> I just want to cross-check in terms of intuitive and consistent variable names.

Regarding the plan4eu model, we have different kind of systems that do storage (and that are treated the same inside the solving model):
* short term hydro storage (which in this nomenclature is 'pumped storage'
* batteries
* load shifting demand-response (which consists in shifting energy from one period to another, and is modelled like a battery)
For all those systems we need variables:
* related to 'volume' constraints (maximum/minimum stored energy in the system)
* related to bounds on the 'instantanous' storage/discharge (which are comparable to Max/Min Active Power for generation plants)
* related to current status of stored energy and of current charging/discharging
* storage efficiency (when 1MWh is 'charged', how much is really available for discharging? 
* probably bounds on charging/discharging gradients
* probably time frames (will be needed for demand-response to handle constraints such as 'energy can be shifted from the period '8am-15am' to the period '16pm-23pm')

**Comment by arght** [comment]
Maximum Storage and Minimum Storage are "static" values independent of the time (e.g., hour). Expressed in GWh
Variable minimum and maximum storage capacity are "dynamic" values depending on the time (e.g., storage hydro reservoir volume profile that may depend on the time of the year). Expressed in GWh
I guess that Maximum Energy Charge corresponds to the dynamic values
Of course, gradients for charging and discharging can be defined

**Comment by sandrinecharousset** [comment]
> Maximum Storage and Minimum Storage are "static" values independent of the time (e.g., hour). Expressed in GWh
> Variable minimum and maximum storage capacity are "dynamic" values depending on the time (e.g., storage hydro reservoir volume profile that may depend on the time of the year). Expressed in GWh
> I guess that Maximum Energy Charge corresponds to the dynamic values
> Of course, gradients for charging and discharging can be defined

Ok understood; but why do we need different names in variable as it would be found from the presnece of not of the subannual? This is how we do in plan4eu. eg for max volume, when only one value is defined it means it is 'static', when a profile is there then means it's 'dynamic' but the variable name is the same.

**Comment by arght** [comment]
OK. No different names are needed.
We can agree on Maximum Storage and Minimum Storage or Maximum Storage and Minimum Storage Capacity

**Comment by sandrinecharousset** [comment]
> OK. No different names are needed.
> We can agree on Maximum Storage and Minimum Storage or Maximum Storage and Minimum Storage Capacity

@arght I think we should not use 'capacity' for naming a variable that deals with amount of energy as capacity is used mainly for 'power' (see all "capacity" variables). Maybe Storage, Minimum storage, Maximum storage ?

**Comment by sebastianzwickl** [comment]
I agree because I also understand capacity intuitively with power.
