### ISSUE TITLE
Economic variables

### ISSUE THREAD

**Issue by hettieboonman** [openENTRANCE/nomenclature#65]
Dear all, 

As mentioned last Thursday, a couple of economic variables could be added. For the energy models, these variables might not be used. However, for generating output, it might be good to also place the economic output in the databases. 

**Here are a couple of my suggestions.** 

1. "Consumption" is currently only referred to as consumption in monetary units. Is this energy consumption only? 

I suggest to adjust this variable as follows: 
- Add consumption (in mln euro) also for non-energy products (e.g. agricultural products, household goods etc). 
- Differentiate between domestic, imported and total consumption in monetary units
- Differentiate between household, government consumption and gross capital formation (investments) and industry consumption. Where industry consumption is defined per industry.

Consumption|Households|Imported|<product>
Consumption|Households|Domestic|<product>
Consumption|Households|Total|<product>
Consumption|Government|Imported|<product>
Consumption|Government|Domestic|<product>
Consumption|Government|Total|<product>
Consumption|GrossCapitalFormation|Imported|<product>
Consumption|GrossCapitalFormation|Domestic|<product>
Consumption|GrossCapitalFormation|Total|<product>
Consumption|<industrie>|Imported|<product>
Consumption|<industrie>|Domestic|<product>
Consumption|<industrie>|Total|<product>

2. Output  (productivity per industry). This indicates whether a sector is benefiting (growing) under certain energy policies. This should therefore also include more industries than just the energy sector. E.g. agricultural, transport, manufacturing sectors. These can be provided in monetary units (million euros).

IndustryOutput|<industry>
ProductOutput|<industry>

3. The use of product factors: capital and labor per industry. Both in monetary units (million euro). My suggestion is: 

Capital|<industry>
Labor|<industry>

4. Price indices. The economic model allows to including prices but not priceindices. Our model does not provide prices but price-indices. A price index is relative with respect to year 2011. That is, in 2011, all price-indices are equal to 1. In later years, the price indices increase or decrease. A priceindex of 1.2 in 2020 for the agricultural sector implies that agri-food prices have increased with 20% with respect to 2011 due to the scenario. I suggest the following price indices

ProductPriceIndex|<product>
CapitalPriceIndex|<industry>
LaborPriceIndex|<industry>

The list of products and industries can be based on an aggregated product and industry definitions from EXIOBASE. Hereby a suggestion: 

<products>
pPLNT	'Crops and vegatable in agri sector'
pANIM   'Animal production'
pFORE   'Forestry and logging'
pFISH   'Fishing and aquaculture'
pFOSM   'Mining fossil fuels'
pOTHM   'Mining of metal ores and non-metallic minerals'
pFBTO   'Manufacturing of food, beverage and tobacco products'
pTXWO   'Manufacturing of textile, wood and printed products'
pCOKE   'Manufacturing of coke products'
pREFN   'Manufacturing of refined petroleum products'
pCHEM   'Manufacturing of chemicals and chemical products'
pRUBP   'Manufacturing of rubber and plastic products'
pNMMP   'Manufacturing of non-metallic mineral products'
pMETP   'Manufacturing of basic metals and metal products'
pELEC   'Manufacturing of electronic computer, optical and electrical equipment'
pMACH   'Manufacturing of machinery and equipment nec and other manufacturing'
pELEQ   'Electricity'
pTRDI   'Transmission and distribution services'
pHWAT   'Steam and hot water supply services'
pWATR   'Collected and purified water, distribution services of water'
pCONS   'Construction'
pTRAD   'Wholesale and retail trade'
pHORE   'Accomodation and food service activities'
pTRAN   'Transportation services'
pREBA   'Real estate, renting and business activities'
pRENT 	'Renting services of machinery and equipment without operator and of personal and household goods (71)' 
pPUBO   'Public administration, education, health and other activities'
pWAST   'Waste for treatment'

<Industries>
iPLNT	'Crops and vegatable in agri sector'
iANIM   'Animal production'
iFORE   'Forestry and logging'
iFISH   'Fishing and aquaculture'
iFOSM   'Mining fossil fuels'
iOTHM   'Mining of metal ores and non-metallic minerals'
iFBTO   'Manufacturing of food, beverage and tobacco products'
iTXWO   'Manufacturing of textile, wood and printed products'
iCOKE   'Manufacturing of coke products'
iREFN   'Manufacturing of refined petroleum products'
iCHEM   'Manufacturing of chemicals and chemical products'
iRUBP   'Manufacturing of rubber and plastic products'
iNMMP   'Manufacturing of non-metallic mineral products'
iMETP   'Manufacturing of basic metals and metal products'
iELEC   'Manufacturing of electronic computer, optical and electrical equipment'
iMACH   'Manufacturing of machinery and equipment nec and other manufacturing'
iELCO         'Production of electricity by coal'
iELGA          'Production of electricity by gas'
iELNU          'Production of electricity by nuclear'
iELHY          'Production of electricity by hydro'
iELWI          'Production of electricity by wind'
iELOI          'Production of electricity by petroleum and other oil derivatives'
iELBI          'Production of electricity by biomass and waste'
iELSO          'Production of electricity by solar photovoltaic or thermal'
iELOC          'Production of electricity by tide, wave, ocean'
iELGE          'Production of electricity by Geothermal'
iELNE          'Production of electricity nec'
iTRDI   'Transmission and distribution services'
iHWAT   'Steam and hot water supply services'
iWATR   'Collected and purified water, distribution services of water'
iCONS   'Construction'
iTRAD   'Wholesale and retail trade'
iHORE   'Accomodation and food service activities'
iTRAN   'Transportation services'
iREBA   'Real estate, renting and business activities'
iRENT	'Renting of machinery and equipment without operator and of personal and household goods'
iPUBO   'Public administration, education, health and other activities'
iWAST   'Waste for treatment'

**Comment by hettieboonman** [comment]
I see that everything between  backets have dissapeared from my 'issue' above. Below I specify the suggested additions again, however, this time without the brackets. Whenever I refer to 'product' or 'industry' I refer to one element from the list defined at the bottom of the issue. 

Consumption|Households|Imported|product
Consumption|Households|Domestic|product
Consumption|Households|Total|product
Consumption|Government|Imported|product
Consumption|Government|Domestic|product
Consumption|Government|Total|product
Consumption|GrossCapitalFormation|Imported|product
Consumption|GrossCapitalFormation|Domestic|product
Consumption|GrossCapitalFormation|Total|product
Consumption|industry|Imported|product
Consumption|industry|Domestic|product
Consumption|industry|Total|product

IndustryOutput|industry
ProductOutput|product

Capital|industry
Labor|product

ProductPriceIndex|product
CapitalPriceIndex|industry
LaborPriceIndex|industry

**Comment by erikfilias** [comment]
@openENTRANCE/modellers , any comments?
 
Also, I can help to make the PR. Do you agree, @hettieboonman ?

**Comment by sebastianzwickl** [comment]
I welcome to set up a PR. This makes the idea more concrete and makes it easier to discuss. The suggested differentiation is reasonable.

**Comment by danielhuppmann** [comment]
Thanks @hettieboonman for this suggestion.

Two questions:

1) Would it make more sense to structure this as:
`Consumption|Households|< product >|Imported`
`Consumption|Households|< product >|Domestic`
so that the total could be written as:
`Consumption|Households|< product >`
(without needing to explicitly write `Total`)?

2) This are more than 50 different product categories. Is this reasonable from a data exchange perspective? Are there other models in the consortium that actually make use of this level of detail?

And one recommendation: to reduce the size of the yaml files, I started PR #64 to define the list of fuel types separately from the variables, using `<fuel>` as short-hand in any variable where any of the fuels could be used. It would make sense to implement a similar structure here (one file with the list of products/industries) and one with the list of variables including a placeholder.

Happy to assist with the necessary implementation on the python side (but also happy to let @erikfilias and @sebastianzwickl take the lead in assisting).

**Comment by hettieboonman** [comment]
Dear all, 

@danielhuppmann : (1) that sounds like a good adjustment. (2) There are actually about 28 products (code starting with a p) and 38 industries (code starting with an i). There are more industries because I have disaggregated the different industries producing electricity for this project. We could further aggregate them off course if necessary. 

@erikfilias and @sebastianzwickl : What is 'making a PR'? If it means that you help to change the nomenclature such that it includes the extra variables as explained in this issue, that would be great! Thanks. Let me know if you need further help from my side. 

Greets, Hettie

**Comment by erikfilias** [comment]
> Dear all,
> 
> @danielhuppmann : (1) that sounds like a good adjustment. (2) There are actually about 28 products (code starting with a p) and 38 industries (code starting with an i). There are more industries because I have disaggregated the different industries producing electricity for this project. We could further aggregate them off course if necessary.
> 
> @erikfilias and @sebastianzwickl : What is 'making a PR'? If it means that you help to change the nomenclature such that it includes the extra variables as explained in this issue, that would be great! Thanks. Let me know if you need further help from my side.
> 
> Greets, Hettie

That's right. Then, we try to add these variables to nomenclature through a pull-request (PR) in the repository. 
I want to  start here only with its definitions:

@hettieboonman . 
Could you check the variables below (its brief description and unit), please?
Variables:

```
Consumption|Households|< product >|Imported:
   description: Consumption of imported product by households
   unit: US$/yr

Consumption|Government|< product >|Domestic:
   description: Consumption of domestic product by households
   unit: US$/yr

Consumption|Government|< product >|Imported:
   description: Consumption of imported product by government
   unit: US$/yr

Consumption|Government|< product >|Domestic:
   description: Consumption of domestic product by government
   unit: US$/yr

Consumption|GrossCapitalFormation|< product >|Imported:
   description: Consumption of imported product in gross capital formation
   unit: US$/yr

Consumption|GrossCapitalFormation|< product >|Domestic:
   description: Consumption of domestic product in gross capital formation
   unit: US$/yr

Consumption|Industry|< product >|Imported:
   description: Consumption of imported product in the industry
   unit: US$/yr

Consumption|Industry|< product >|Domestic:
   description: Consumption of domestic product in the industry
   unit: US$/yr
```
I'm not sure about the description and unit of the next variables. Could you bring us these details, please?
```
IndustryOutput|industry
ProductOutput|product

Capital|industry
Labor|product

ProductPriceIndex|product
CapitalPriceIndex|industry
LaborPriceIndex|industry
```

Any comment?

**Comment by hettieboonman** [comment]
@erikfilias  thank you for making the suggestion. Hereby some adjustments: 

Consumption|Households|< product >|Imported:
   description: Consumption of imported product by households
   unit: million euro/yr

Consumption|Government|< product >|Domestic:
   description: Consumption of domestic product by households
   unit: million euro/yr

Consumption|Government|< product >|Imported:
   description: Consumption of imported product by government
   unit: million euro/yr

Consumption|Government|< product >|Domestic:
   description: Consumption of domestic product by government
   unit: million euro/yr

Consumption|GrossCapitalFormation|< product >|Imported:
   description: Consumption of imported product by gross capital formation
   unit: million euro/yr

Consumption|GrossCapitalFormation|< product >|Domestic:
   description: Consumption of domestic product by gross capital formation
   unit: million euro/yr

Consumption|Industry|< product >|Imported:
   description: Consumption of imported product by industries
   unit: million euro/yr

Consumption|Industry|< product >|Domestic:
   description: Consumption of domestic product by industries
   unit: million euro/yr



**And hereby the description and unit of the other variables:** 

IndustryOutput|industry
    description: Total output on the industry level
    unit: million euro/yr

ProductOutput|product
    description: Total output on the product level
    unit: million euro/yr

Capital|industry
    description: Total capital costs spend by industry
    unit: million euro/yr

Labor|< industry >
    description: Total wages spend by industry
    unit: million euro/yr

ProductPriceIndex|product
    description: Price index on the product level, relative to base year 2011
    unit: index equals 1 in 2011, the reference year

CapitalPriceIndex|industry
    description: Price index of capital, relative to base year 2011
    unit: index equals 1 in 2011, the reference year

LaborPriceIndex|industry
    description: Price index of wages, relative to base year 2011
    unit: index equals 1 in 2011, the reference year

Thanks for making the pull request! 

Greets, hettie

**Comment by hettieboonman** [comment]
@danielhuppmann 
Dear Daniel, do you need more information from my side to merge this code with the economic variables in the nomenclature? 

Greets, Hettie

**Comment by hettieboonman** [comment]
Dear Eric, 

As mentioned in the teams meeting this morning, some minor changes to the variables are requested. That is, the definition of the products and industries: 
Hereby the new list: 

**List with products:**
pAGRI	 'Agriculture'
pINDU	 'Manufacturing industry'
pALUM	 'Aluminium production'
pSERV	 'Services'
pTRAN	 'Transport services'
pELEC	 'Electricity'
pTRDI	 'Trade and distribution services of electricity'
pHTWT	 'Steam and hot water supply'
pOIL	 'Crude Oil'
pGSL	 'Gasoline'
pDSL	 'Diesel'
pHDI	 'Heavy distillate'
pNG	 'Natural gas'
pCOA	 'Coal'
pBIO	 'Biofuels'
pFUL	 'Other fuels'
pH2	 'Hydrogen'

**List with industries:** 
iAGRI	 'Agriculture'
iCOAL	 'Coal extraction'
iCOIL	 'crude oil and natural gas extraction'
iINDU	 'Manufacturing industry'
iALUM	 'Aluminium production'	
iTRDI	 'Trade and distribution services of electricity'
iNGAS	 'Natural Gas'
iSERV	 'Services'
iTRAN	 'Transport services'
iELCC	 'Production of electricity by coal'
iELCG	 'Production of electricity by gas'
iELCN	 'Production of electricity by nuclear'
iELCH	 'Production of electricity by hydro'
iELCW	 'Production of electricity by wind'
iELCO	 'Production of electricity by petroleum and other oil derivatives'
iELCB	 'Production of electricity by biomass and waste'
iELCS	 'Production of electricity by solar photovoltaic'
iELCE	 'Production of electricity nec'
iELCT	 'Production of electricity by Geothermal'

Note that we only need to have the product and industry code: i.e. "iELCT, iELCE etc", the description is just extra information. 

Is it possible for you to review and update the nomenclature next week? Then I will try to write that to the platform. 

Greets, Hettie

**Comment by erikfilias** [comment]
Hi @hettieboonman, please check #68 .
I tried to modify the yaml files according to the new lists, and follow the suggestion from Daniel.

Best, Erik

**Comment by hettieboonman** [comment]
Dear Erik,

I briefly looked through the changes, but changes look good! (They are not yet pushed to the economy.yaml file right?) Because I did not see the changes there yet? 

Greets, Hettie

**Comment by erikfilias** [comment]
HI @hettieboonman , I've just added the variables `Consumption|Households`, `Consumption|Government`, and `Consumption|Industry`, please check [here](https://github.com/openENTRANCE/nomenclature/pull/68/files).
Have you been referring to those variables?
