### ISSUE TITLE
Review variables/units and add relevant nomenclature for `GENeSYS-MOD`

### ISSUE THREAD

**Issue by tburandt** [openENTRANCE/nomenclature#7]
This will review the first set of variables/units and add a list of variables relevant for `GENeSYS-MOD`. It should not add (at this stage) all required variables (to not have a PR too large to review), but rather see whether the process for adding variables and units is sufficiently simple and intuitive.

depends on #4

**Comment by danielhuppmann** [comment]
closing per merge of #36 and #48
