### ISSUE TITLE
Inconsistency in the subcountry definitions (of France)

### ISSUE THREAD

**Issue by philipphaertel** [openENTRANCE/nomenclature#72]
There seems to be some inconsistency in the [subcountries.yaml](https://github.com/openENTRANCE/nomenclature/blob/master/nomenclature/definitions/region/subcountries.yaml) definitions of the French subgrid regions.

Specfically, the following nuts regions cannot be found in the [nuts3.yaml](https://github.com/openENTRANCE/nomenclature/blob/master/nomenclature/definitions/region/nuts3.yaml) (or recent shape layer information from https://gisco-services.ec.europa.eu/distribution/v2/nuts/):
Cannot find nuts id FR613
Cannot find nuts id FR627
Cannot find nuts id FR824
Cannot find nuts id FR515
Cannot find nuts id FR246
Cannot find nuts id FR715
Cannot find nuts id FR521
Cannot find nuts id FR252
Cannot find nuts id FR223

If it is not possible to match the definition with current NUTS versions used in the [nuts3.yaml](https://github.com/openENTRANCE/nomenclature/blob/master/nomenclature/definitions/region/nuts3.yaml) definitions (2016/21), it might help to further specify the NUTS version the subregion definition is referring to.

Thanks

**Comment by danielhuppmann** [comment]
Indeed, thank you @philipphaertel for highlighting this error...

This was added by in PR #20. @sandrinecharousset, could you please review the mapping of ehighways2050 regions to NUTS-codes? For reference, the xlsx source file used to generate the NUTS-region classification is available in a separate branch [danielhuppmann:attachment/nuts-regions](https://github.com/danielhuppmann/nomenclature/tree/attachment/nuts-regions)  (see the `region/data` folder).

**Comment by sandrinecharousset** [comment]
@philipphaertel thank you for noticing this
The error came from a bug in the macro converting nuts2013 to nuts 2021 (as ehighway uses the nuts2013 nomenclature and we are using nuts2021....)
I have corrected all subregions for france

**Comment by philipphaertel** [comment]
Thanks for fixing the definitions, @sandrinecharousset 
New definitions work on my end.
