### ISSUE TITLE
Small adjustments to economic variables 

### ISSUE THREAD

**Issue by hettieboonman** [openENTRANCE/nomenclature#77]
Dear all, 

@erikfilias and @danielhuppmann , first of all sorry. I know it took some time before the last issues/ pull requests had been approved. Today I converted my model output in the format of the platform, and I found that there were some inconsistencies. 

Below I summarize the (small) changes that are required: 

**Unit conversions (see also other issue). Replace billion US dollar by Million Euro**

Consumption:
description:   Total consumption of all goods, by all consumers in a region
unit: million euro/yr
 
Consumption|Households:
description:   Total consumption of all goods, by households in a region
unit: million euro/yr
 
Consumption|Government:
description:   Total consumption of all goods, by the government in a region
unit: million euro/yr
 
Consumption|Industry:
description:   Total consumption of all goods, by industries in a region
unit: million euro/yr

GDP|MER:
description: GDP at market exchange rate
unit: million euro/yr

**A little mistake/ inconsistency  in variable name (replace "Government" by "Households" in the variable name)** 

Consumption|Households|<Product>|Domestic:
description: Consumption of domestic <this product> by households
unit: million euro/yr

**I made a mistake in the  price index of capital and region. They are not defined per industry, only by region**

Capital Price Index:
description:   Price index of capital from <this industry>, relative to base year 2011
note: The index   equals 1 in 2011, the reference year
unit: ''
 
Labor Price Index:
description:   Price index of wages from <this industry>, relative to base year 2011
note: The index   equals 1 in 2011, the reference year
unit: ''

Greets, Hettie

**Comment by erikfilias** [comment]
Hi @hettieboonman, I've just created a PR (see #81 ). The replacement of billion US dollars by Million Euro is waiting that will be defined in order of agreements reached in #76.
Please check it.

**Comment by hettieboonman** [comment]
@erikfilias  Thank you for your quick response. See also my comment to the other 'issue', I think that the preference for most modelers is to use million euro rather than billion dollar. Also because this consortium has mostly (only?) European energy models. Also, regions that are defined, are only European regions.
