### ISSUE TITLE
Validate units related to variables

### ISSUE THREAD

**Issue by danielhuppmann** [openENTRANCE/nomenclature#82]
Discussion #76 made me realize that the `nomenclature.validate()` function does not (yet) perform a validation whether the reported unit is in line with the nomenclature.

I recently wrote a little script for another project, it would be great if someone would volunteer to merge the unit-related part into the `validate()` function (and also make sure that this works for lists of allowed units, see https://github.com/openENTRANCE/nomenclature/issues/76#issuecomment-727892909).

@erikfilias @sebastianzwickl, would you have an hour to give this a try?

Note: `variable_config` is roughly equivalent to the `nomenclature.variables` dictionary.

```python
    # validate variables and against valid template
    illegal_vars, illegal_units = [], []

    for i, (var, unit) in df.variables(include_units=True).iterrows():
        if var not in variable_config:
            illegal_vars.append(var)
        elif unit != variable_config[var]['unit']:
            illegal_units.append((var, unit, variable_config[var]['unit']))

    if illegal_vars:
        msg = 'The following variables are not defined in the project template:'
        log.error('ERROR: ' + '\n - '.join([msg] + illegal_vars) + '\n')

    if illegal_units:
        msg = 'The following units are not in line with the project template:'
        lst = [f'{v} - expected: {e}, found: {u}' for v, u, e in illegal_units]
        log.error('ERROR: ' + '\n - '.join([msg] + lst) + '\n')
```

**Comment by sebastianzwickl** [comment]
thank you @danielhuppmann - I will have a look at this in the next couple of days. Gladly in coordination with @erikfilias

**Comment by danielhuppmann** [comment]
Thank you! Let me know if something is not clear, happy to assist!

**Comment by erikfilias** [comment]
> thank you, @danielhuppmann - I will have a look at this in the next couple of days. Gladly in coordination with @erikfilias

I'm also glad to collaborate!:D

**Comment by sebastianzwickl** [comment]
Quick update: I have started and already tested with a dummy file. The comprehensive _test_functions_ are still missing and then I start the pull request. I will do this until Monday at the latest.
