### ISSUE TITLE
How to write euro

### ISSUE THREAD

**Issue by sandrinecharousset** [openENTRANCE/nomenclature#85]
It seems that euro sometimes is writte 'euro', sometimes '€'
I had problems in my python scripts with the '€' (but very probably there is sth to do about it, just I am not aware of it, if anyone knows, in advance thank you)
Anyway, we should chose one unique way of writting euro

**Comment by danielhuppmann** [comment]
Given that nobody expressed a preference here yet, I suggest to use `EUR`. Please use reactions (thumbs up/down) to vote. @openENTRANCE/modellers

**Comment by hettieboonman** [comment]
I vote for 'euro' rather than the symbol of a euro: '€'. 

Greets, Hettie

**Comment by sandrinecharousset** [comment]
I am indifferent but would prefer to avoid '€'  (unless someone explains to me how to deal with '€' in python scripts)
EUR is fine

**Comment by danielhuppmann** [comment]
# Decision: `EUR`

(Vote 7 to 1)

Closing this issue so that we can proceed with implementation.
