### ISSUE TITLE
Improve description of data format for year/value on landing page

### ISSUE THREAD

**Issue by danielhuppmann** [openENTRANCE/nomenclature#9]
Per bilateral communication with @tburandt, the section on **Timeseries data dimensions** is not sufficiently clear in the top-level [README](https://github.com/openENTRANCE/nomenclature/blob/master/README.md) because **year** and **value** are not mentioned. I didn't include them in my first version because they do not require subfolders with more detailed explanation, and I was worried about creating confusion about *long vs. wide table formats*.

So how to add this information in a concise and intuitive way:

1. Add entries to the 
   > 7 Year
   > 8 Value
   
   But this risks confusion because it might be understood that it has to be a long format (it can be either long or wide).

2. Come up with a short description after the list of dimensions (good formulations?)

3. Option 2 but also add example tables (one long, one wide) similar to what is in the [pyam-docs](https://pyam-iamc.readthedocs.io/en/stable/data.html) or [this tutorial](https://pyam-iamc.readthedocs.io/en/latest/tutorials/data_table_formats.html) -but this has the risk of making the top-level README very long...

**Comment by danielhuppmann** [comment]
@burandt @erikfilias any ideas or comments?

**Comment by erikfilias** [comment]
@danielhuppmann, `option 1` could generate some confusion between dimensions subannual and year. I think if we do not consider the dimension subannual and add year and value could generate a great number of rows in the files.
Whilst `option 2` could show some examples of good formulation and not add new dimensions (year and value). The image for the illustrative example of IAMC-format time series data in the [pyam-docs](https://pyam-iamc.readthedocs.io/en/stable/data.html) is great for this purpose, I think. For me, option 2 is suitable for our purposes.
