### ISSUE TITLE
Removal of LoadFactor variables within PR #91

### ISSUE THREAD

**Issue by tburandt** [openENTRANCE/nomenclature#94]
@danielhuppmann 

Why have those variables been removed from the nomenclature within PR #91:

`LoadFactor|Electricity|Solar|Profile`
`LoadFactor|Electricity|Wind|OffShore|Profile`
`LoadFactor|Electricity|Wind|OnShore|Profile`

I am unable to find an appropriate substitute variable for those, maybe I have overlooked something

**Comment by danielhuppmann** [comment]
Apologies, my mistake - I thought that I was just removed duplicates in that PR.

Can you make a PR re-introducing those, but with the correct spelling (see #93) and without a "Profile" tag (see #92).
